name: masamune_ads
description: >-
  Library that provides advertising system of Masamune framework.
  Use Admob etc.
version: 0.8.2+3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_ads

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  masamune: ^0.8.0
  google_mobile_ads: ^0.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
